### ISSUE TITLE
Default tag name from class name 

### ISSUE THREAD

**Issue by blelump** [trailblazer/formular#11]
Hi @fran-worley ,

I've found that quite annoying, when building custom elements,  eg:
```
    class DocumentsForm < BaseForm
      set_default :enctype, "multipart/form-data"
    end
```
it sets tag name as `documents_form`. I know that with practice comes experience which eventually becomes a mastery :smile: , but defining every time what tag should be used, seems to introduce another unnecessary complexity, eg:
```
   BaseForm = Class.new(Formular::Elements::Form) do
      tag :form
      set_default :class, %w(form-horizontal)
   end

    class DocumentsForm < BaseForm
      tag :form # Here tag is needed as well
    end
```

Perhaps we could use `inheritable_attr` for tag and do not create tag name from class name? Yesterday I've tried to find why it wasn't working and it was caused by invalid tag. Class name was `Radio` so I even forgot that there's no such tag. Just blindly tried to find a non existing bug :smile: .

**Comment by fran-worley** [comment]
This is exactly what I had intended to do. Glad we are on the same page :)

**Comment by fran-worley** [comment]
Done! 😄 https://github.com/trailblazer/formular/commit/8c6fddab3c18afe9564a621b72be67afa54e6df0

FYI, I've added some extra base classes for Div, Span and P so you can inherit from those and not need the tag line.
