### ISSUE TITLE
Collection with custom builders?

### ISSUE THREAD

**Issue by blelump** [trailblazer/formular#13]
Hi @fran-worley ! :smile: 

The problem:
![img](http://i.imgur.com/e4KbI6q.png)

The former input (birth country) is wrapped by `div.col-sm-6`, the latters (each row element) is `div.col-sm-2`. So what I have had in the old Formular was the ability to extend nested collection with additional builder (eg: `= f.nested(:language_profficiencies, Formular::HorizontalRow) do |g|` ) and hence, use different context within the same form. Do you have any ideas how to bite that?

So far, here I'd go the same way, because [`Wrapper`][2] type sets default class for certain builder class. I'm also thinking about the hard way, eg:
```
element_set({
                  another_wrapper: AnotherWrapper
})
```
and then try to patch `Input` or `Select` wrapped [block][1], but it doesnt seem to be the behaviour we'd like to have in new Formular. I mean its responsibility is to render label + tag wrapped by extra element, defined by `wrapper` in element set. I am sure, however, that one form may have multiple wrappers, because of the form infinite possible structures.

[1]: https://github.com/trailblazer/formular/blob/98b4aa03008533d96ad7edf5b13a0b5990d914fa/lib/formular/elements/bootstrap3/horizontal.rb#L23
[2]: https://github.com/trailblazer/formular/blob/98b4aa03008533d96ad7edf5b13a0b5990d914fa/lib/formular/elements/bootstrap3.rb#L52

**Comment by fran-worley** [comment]
I've added a builder option to nested and collection. 

```ruby
f.nested(:name, builder: SomeBuilderClass) do |b|
  # and we add our nested content here
end
```

The builder option defaults to the current builder class.

**Comment by blelump** [comment]
Damn, you're fast! Let me check

**Comment by blelump** [comment]
@fran-worley ,

what would you say if I'd like to achieve smth like:
```
element_set({
                  horizontal_collection: HorizontalColl
    })

# and then

= f.horizontal_collection(:language_profficiencies) do |g|
```

It's just prettier instead of having additional builder type defined in a view. But that's mixing elements with builders in `element_set`.

**Comment by fran-worley** [comment]
What you could do is define the method in your builder to make use of the option:

```ruby
class MyFancyBuilder < Formular::Builders::Basic
  def horizontal_collection(name, **options, &block)
    options[:builder] = HorizontalCollection
    collection(name, **options , &block)
  end
end
```

**Comment by blelump** [comment]
@fran-worley , exactly!

Well, I think this is huge improvement as it introduces a feature to customize (possible nested) graph with custom builders, where each builder provides its own behaviour. 

Huge thanks for https://github.com/trailblazer/formular/commit/59449f347bbcba6790d851c0c4c7df0b21c50fea !

ps. I've tried to find an use case for not nested elements and a requirement of having eg. two inputs in one row, but I think that's achievable simply in a view. No need to add additional complexity to Formular.

**Comment by fran-worley** [comment]
I agree, and you're welcome. If you've got a set, can you take a look at #12. I want to merge it but don't want to break your code...
