### ISSUE TITLE
Ignore wrapper for certain element type

### ISSUE THREAD

**Issue by blelump** [trailblazer/formular#15]
Hi @fran-worley ,

I wonder about possible solutions, where you'd need an element, where builder is based upon Bootstrap and you want to ignore wrapper element (eg. input type hidden). So far I'm having smth like this:
```
  class Hidden < Formular::Elements::Input
    set_default :type, 'hidden'
  end

    element_set({
                  hidden: Hidden
    })
```

I'm fine with such approach, but I think hidden type can be generic and always defined without wrapper element, regardless of whether you use a front–end decorator (BS, Foundation) or default builder.

**Comment by fran-worley** [comment]
There is a basic 'hidden' element at `Formular::Elements::Hidden`

**Comment by blelump** [comment]
Uhm, indeed. What do you think to inject it into all builders ?

**Comment by fran-worley** [comment]
I could define it as a method on `Formular::Builders::Basic` which they all inherit from. That way if you pass in a hidden element it will override the base method.

**Comment by fran-worley** [comment]
That or we enable the inheritance of element sets...
