### ISSUE TITLE
Rendering select element with extra options

### ISSUE THREAD

**Issue by blelump** [trailblazer/formular#18]
oi @fran-worley ,

I'd suggest to follow (again) the [AV library][1] in the case of rendering `select` options. I mean, to have third element from an array as options for `option` tag, eg:
```
[[name, id, extra_ops = {'data-smth': 'ok'}], [name, id, extra_ops = {}]]
```
which result in:
```
<option value="id" data-smth="ok">name</option>
<option value="id">name</option>
```

[1]: http://api.rubyonrails.org/classes/ActionView/Helpers/FormOptionsHelper.html#method-i-options_for_select

**Comment by fran-worley** [comment]
I actually hadn't realised this was a feature and AV.

This needs supporting, we just need to make sure that we don't break anything. 

This thread covers things to consider when supporting more than just a basic array.
https://github.com/plataformatec/simple_form/issues/188
