### ISSUE TITLE
Formular crashes if set_default is a symbol

### ISSUE THREAD

**Issue by blelump** [trailblazer/formular#2]
Hi @fran-worley !

I'm exploring new formular and you're doing really good job! However :smile: , I'd like to add a proposal. I mean, according to the comments [here][1], the `:symbol` is treated as a method name. I must admit, I haven't seen such solution yet and I'd propose perhaps a more common approach, where if something quacks like a `call`, then it must be callable, eg: `set_default :required, -> { 'required' }`. Well, it's actually working already in such manner :smile: .

I think it would be more common and reliable approach. What do you think?

[1]: https://github.com/trailblazer/formular/blob/master/lib/formular/element.rb#L95

**Comment by fran-worley** [comment]
Ahh yes, this appears to be a classic case of not updating comments when changing code.

This now uses @apotonick Uber gem to evaluate the hash. This is the same piece of code used by Reform to evaluate prepopulate and populate so it *should* work in exactly the same as Reform.

I'll update the comment to reflect. Sorry for any confusion!

**Comment by blelump** [comment]
Got it! :smile: 

Closing.
