### ISSUE TITLE
:escape_html option for builder methods

### ISSUE THREAD

**Issue by cdennl** [trailblazer/formular#29]
When I input 

> &lt;p&gt;"test"&lt;/p&gt;

in a `f.input :my_text` it breaks my form on rerendering with the value. To make it work I have to do `f.input :my_text, value: html_escape(f.model.my_text)`

I'd like to have an option `escape_html` which defaults to `true`, which does this

**Comment by fran-worley** [comment]
If it we escape the html then it will also be saved in its escaped format is that what you want?

If you need the actual html (i.e. for some kind of CMS) you'll have to use a text area as you'll end up with invalid html otherwise.

**Comment by cdennl** [comment]
No, if it is done correctly no escaped HTML is inserted, I show you what happens.

First case, without escaping:

```
= f.input :title, class: 'form-control'
= f.input :game_title, class: 'form-control'
```

insert these values:

```
title: <b>"test"</b>
game_title: <b>test</b>
```

this is sent to the server:

```
Parameters: {"challenge"=>{"title"=>"<b>\"test\"</b>", "game_title"=>"<b>test</b>"}}
```

but rerendering yields:
```
<input class="form-control" name="challenge[title]" id="challenge_title" value="<b/>"test"</b/>" type="text"/>
<input class="form-control" name="challenge[game_title]" id="challenge_game_title" value="<b/>test</b/>" type="text"/>
```

which is wrong, because somehow `/` are falsely appearing

Second case, with escaping:
```
= f.input :title, class: 'form-control', value: ERB::Util.h( f.model.title )
= f.input :game_title, class: 'form-control', value: ERB::Util.h( f.model.game_title )
```

with same input, it rerenders:

```
<input class="form-control" value="&lt;b&gt;&quot;test&quot;&lt;/b&gt;" name="challenge[title]" id="challenge_title" type="text"/>
<input class="form-control" value="&lt;b&gt;test&lt;/b&gt;" name="challenge[game_title]" id="challenge_game_title" type="text"/>
```

and resubmission of this yields:

```
Parameters: {"challenge"=>{"title"=>"<b>\"test\"</b>", "game_title"=>"<b>test</b>"}}
```

which is the desired behaviour. No escaped markup is passed to the server and form rerenders fine.

**Comment by fran-worley** [comment]
Ok so I've done some digging into this and discovered that there was a bug causing your extra `/` not browsers (though some will do crazy things to invalid html markup).

This bug is fixed on master via https://github.com/trailblazer/formular/commit/614985e25d869b74515f97f200e1d7b8247f1a0e and I'll add an 'escape' option which will be turned on by default.

**Comment by cdennl** [comment]
Awesome, I'll test it out.

**Comment by cdennl** [comment]
I tested it and the `/` is not appearing anymore, escape_html true as default seems reasonable to me. Thank you.

**Comment by aiomaster** [comment]
This html escaping stuff makes me a little scary! If we don't do it right, we help to build large security holes. I tried to fix the obvious things like the values on inputs and the content of a textarea. (#33)
In most cases the options of a checkbox, radio_button or select field are no user input, so there should be no problem. If user input is used there one should take care of escaping, that seems ok. Are there other things, where user input is a problem?

**Comment by fran-worley** [comment]
I completely agree that this is an important issue to get right.

See fdd4ecc540db13e28c675a6c76932e4f2251c603 and 2ba90c2849af01d723b477cadc786d182df65862

This covers areas of user input and a couple of extras to improve html validity (eg. errors, hints and labels). These modules are pretty flexible so if we find other areas or we decide to make escaping optional it will be super simple.
