### ISSUE TITLE
Password input is missing

### ISSUE THREAD

**Issue by sergey-koba-mobidev** [trailblazer/formular#30]
Hi, thank you for gem,

Am I unable to find or password input is missing ?

**Comment by fran-worley** [comment]
Hi @sergey-koba-mobidev I'm glad you've found it useful.

The gem is designed to reflect the HTML tags for inputs. A password field is actually an input tag with a type attribute of 'password' so to create a password field you can simply call `f.input(type: :password)`

The same applies for other input types like numbers, ranges, etc.

**Comment by sergey-koba-mobidev** [comment]
Hm... sounds reasonable, closing this. Thank you!
