### ISSUE TITLE
Formular::Helper.builder = :bootstrap3 not working

### ISSUE THREAD

**Issue by sergey-koba-mobidev** [trailblazer/formular#31]
Hi @fran-worley, 

I am trying to set Bootstrap3 as global builder (in my config.ru) after requiring 'formular' like so:
`Formular::Helper.builder = :bootstrap3`

But it doesn't help until I do it inside my view:
`<% f = form(model, '', builder: :bootstrap3) %>
<%= f.start %>`

Maybe I am again doing something wrong :)

**Comment by zavan** [comment]
I have the same issue, but I'm doing `Formular::Helper.builder = :bootstrap3` in a Rails initializer.

**Comment by fran-worley** [comment]
This has been fixed via 78a88c90353d0e84b477bb0d653a829b50b909b0
