### ISSUE TITLE
[bug] Error messages not shown properly with bootstrap 4 slim

### ISSUE THREAD

**Issue by emaglio** [trailblazer/formular#36]
Ciao @fran-worley and @apotonick, 
this is the html generated when there is an error:
```
<fieldset class="form-group has-danger"> 
  <input placeholder="Title" name="title" id="title" value="" class="form-control" type="text">
  <span class="form-control-feedback">Error Message</span>
</fieldset>
```
this looks quite bad: 
![not cool](https://cloud.githubusercontent.com/assets/5493507/24594839/49503f02-1874-11e7-9cf3-a0ad33da6378.png)
In base on the docs (https://bootstrapdocs.com/v3.3.6/docs/css/#forms-control-validation) the span is used for the icon and not for text.

To fix this I found a bootstrap validator (http://1000hz.github.io/bootstrap-validator/) that gives a solution when an error message needs to be shown and the html is:
```
<fieldset class="form-group has-feedback has-error has-danger">
 <input placeholder="Title" name="title" id="title" value="" class="form-control" type="text">
 <span class="form-control-feedback"></span> 
 <div class="help-block with-errors">
   <ul class="list-unstyled"> 
     <li>Error Message</li> 
   </ul>
  </div>
</fieldset>
```
this makes the error message shown way better but still not the best, probably it depends on my CSS as well:
![way better now](https://cloud.githubusercontent.com/assets/5493507/24594899/d8d9938a-1874-11e7-98de-c615a356d582.png)

I guess that the problem is in the `list-unstyled`, I have added `h6 text-left` just to make it looks better but I don't think it's the correct solution:
![better](https://cloud.githubusercontent.com/assets/5493507/24594944/3ebf4ffa-1875-11e7-9df6-f9b5376f08cf.png)

I have already "fixed" the code in order to create the html as per the validator:
https://github.com/emaglio/formular/blob/error_slim/lib/formular/element/bootstrap4.rb#L44
https://github.com/emaglio/formular/blob/error_slim/lib/formular/elements.rb#L131
but before going ahead, it would be great to have some feedbacks from you guys about the solution that I have found.

ciao

**Comment by fran-worley** [comment]
Sorry for the delay on this. It looks like Bootstrap 4 docs have changed since I drafted this. now updated as per the official docs:
https://github.com/trailblazer/formular/commit/a314f5bfa2310f4619aa4e53f48aaa46586e6495
