### ISSUE TITLE
Add support for "multiple" option in select element 

### ISSUE THREAD

**Issue by Titinux** [trailblazer/formular#40]
*I'm using formular master branch*

The select element should be smarter with 'multiple' option.

Currently :
```ruby
f.select(:offer_ids, collection: offers_collection, multiple: 'multiple', name: 'inode[offer_ids][]')
```

I expect select element add the tag attribute multiple: "multiple" and add [] at the end of the name
```ruby
f.select(:offer_ids, collection: offers_collection, multiple: true)
```

**Comment by fran-worley** [comment]
@Titinux Completely agree RE setting the name attribute correctly. However is there much point in mucking about with the multiple value? Per the HTML spec its just a boolean attribute so the value itself doesn't matter.

**Comment by Titinux** [comment]
@fran-worley I re-read html5 spec (https://dev.w3.org/html5/spec-preview/the-select-element.html#attr-select-multiple) and you are totally right. The value doesn't matter at all, even no value at all is right as long as the attribute is present.

```html
<input type=checkbox checked name=cheese disabled>
```
is valid. 

🙇 thanks for the commit and for pointing my misunderstanding.
