### ISSUE TITLE
Question regarding builder

### ISSUE THREAD

**Issue by joep** [trailblazer/formular#47]
Ideally, I'd like to add some of my own elements to an existing builder. The approach that seemed most obvious to me doesn't appear to work, e.g.,

```
require 'formular/builders/bootstrap3'
class MyBuilder < Formular::Builders::Bootstrap3
  element_set(
    # my additional elements here
  )
end
Formular::Helper.builder = MyBuilder
```
As some point, it always tries to load 'formular/builders/MyBuilder'

So the question is, what is the best approach to use?

Thanks!

**Comment by fran-worley** [comment]
@joep up until just now the helper only worked with built in Builders.

Fancy giving it a go now (from master obvs)?

**Comment by joep** [comment]
Sure, appears to be simple enough if this looks like the right approach to you.

**Comment by joep** [comment]
Uh, it actually looks like this was done in the last commit?

**Comment by fran-worley** [comment]
yeah, you should be good to go :)

**Comment by fran-worley** [comment]
If you need elements for a specific form, you can also add pass them into your form call as an option e.g.
`form(model, url, elements: {super_special_label: MyLabel})` 

Elements here will be merged with those of the builder being used.

**Comment by joep** [comment]
Ah, ok. This is a pretty slick system you guys have, Formular + Reform. From start to finish, I managed to add a recaptcha element to the form, complete with validation by Reform in just a couple of hours, not including the first few hours of stumbling around with the documentation before realizing I needed to dig a little deeper into the code.

Thanks for your work!
