### ISSUE TITLE
Ideas for rendering radio buttons

### ISSUE THREAD

**Issue by blelump** [trailblazer/formular#5]
Hi @fran-worley ,

so I am exploring builder features and rendering a radio button group. It is given as:
![img](http://i.imgur.com/hF2oHt8.png) . 

I've ended up with overriding `checkable_label` method, in particular:
```
      def checkable_label
        label_opts = Formular::Attributes[options[:label_options]]
        label_opts[:content] = "#{to_html(context: :default)} #{Span.call(content: " ")} #{options[:label]}"
        Formular::Elements::Label.(label_opts).to_s
      end
```

where `Span` type is given as:
```
      class Span < Formular::Elements::Container
        tag :span
        set_default :class, ['icon-controller-record']
      end
```

Am I violating some private API (`checkable_label`) ? Perhaps any ideas to improve this piece of code ? Thanks!

**Comment by fran-worley** [comment]
I'll have a think about whether there is a better way of doing this, I've already made a couple of minor changes on master which should clean things up a little:

```ruby
      def checkable_label
        label_options[:content] = "#{to_html(context: :default)} #{Span.()} #{label_text}"
        Formular::Elements::Label.(label_options).to_s
      end
```

**Comment by blelump** [comment]
@fran-worley , I'm thinking on it, but I'd consider changing the flow as the `checkable_label` shouldn't be responsible for rendering the label content. I mean it's fine until label content is just a simple text, but when some more complex use cases appear, `checkable_label` renders input, smth and finally label text (current use case). Perhaps extraction of label content would be a good start?
