### ISSUE TITLE
Bootstrap4::Submit - default CSS classes take precedence over the defined classes

### ISSUE THREAD

**Issue by anton-yordanov** [trailblazer/formular#53]
```
= form.submit content: "SIgn In", class: ["btn-lg", "btn-block", "mt-3", "btn-primary"]
```
Returns
```
<div class="form-group">
  <button class="btn-lg btn-block mt-3 btn-primary btn btn-secondary" type="submit">Sign in</button>
</div>
```
The side effect is that ```btn-secondary``` class take precedence over my ```btn-primary``` class.
I expect the custom CSS classes to be appended to the defaults and to take precedence over them.
```
<div class="form-group">
  <button class="btn btn-secondary btn-lg btn-block mt-3 btn-primary" type="submit">Sign in</button>
</div>
```

**Comment by fran-worley** [comment]
When dealing with css the order in which the classes appears in your html makes no difference. The bootstrap css declares `btn-secondary` after `btn-primary` so it will always tack precedence.

The only fix here is to either provide a way for you to override the default classes, or provide some bootstrap friendly options for setting these classes (size, color, block etc.).

I'm leaning to the latter as I don't really want to add a load of array mutating options into the underlying element class

**Comment by fran-worley** [comment]
@anton-yordanov I've just added something to [master](https://github.com/trailblazer/formular/commit/027dc685f198c4cbf76a0163620d4c0fd1adbf2d) which should work for you.

**Comment by anton-yordanov** [comment]
Yes, the order of the css classes makes no difference, sorry about that. 
Thanks for the fix.
