### ISSUE TITLE
0.1.0 release?

### ISSUE THREAD

**Issue by blelump** [trailblazer/formular#8]
Hi @fran-worley , 

I think the code is ready to release at least 0.1.0. So far I've prepared 2 kinds of form objects and I am really satisfied with the results. 

The builder and form elements customization help here a lot, however I'd think about making it yet more flexible. I know this is diffcult to achieve everything, but that's the real power of this library  ! :smile:

**Comment by fran-worley** [comment]
I'm glad you like it. I've got one pending change to make to how default options/ attrs are merged in and then I'll release.

I'm all for making it 'yet more flexible' so feel free to post some examples/ dreams/ ideas and I'll see what I can do :).

**Comment by fran-worley** [comment]
Done. Note that the initial release is actually v0.2.0  as @apotonick had released the old formular as v0.1.0
